language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - cargo install cargo-travis || echo "cargo-travis already installed"

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

after_success:
  - cargo doc
  - cargo doc-upload
