language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

after_success:
  - cargo doc
  - git checkout gh-pages
  - mv target/doc doc
  - git add doc
  - git commit -m "update docs"
  - git push
