[package]
name = "confertus"
authors = ["Felix Karg <f.karg10@gmail.com>"]
repository = "https://github.com/fkarg/confertus"
readme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
